import Head from 'next/head'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Next !</h1>
      </main>

      

      <footer>
        <script src="https://unpkg.com/react/umd/react.production.min.js" crossorigin></script>

        <script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js" crossorigin></script>

        <script src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js" crossorigin></script>
      </footer>
    </div>
  )
}
